### 주문 생성
POST http://localhost:9090/api/v1/orders
Content-Type: application/json

{
  "price": "{{$random.integer}}"
}

### 주문 조회
@orderId = 852f0917-47c0-49e1-bcaf-050333f8456f
GET http://localhost:9090/api/v1/orders/{{orderId}}

### 주문 취소
PUT http://localhost:9090/api/v1/orders/{{orderId}}/cancel


