### 주문 생성
POST http://localhost:9090/api/v1/orders
Content-Type: application/json

{
  "price": "{{$random.integer}}"
}

### 주문 취소
@orderId = c31f9049-c6c2-4fa6-96f5-11aca0d0ac1a
PUT http://localhost:9090/api/v1/orders/{{orderId}}/cancel


