### 주문 생성
POST http://localhost:9090/api/v1/orders
Content-Type: application/json

{
  "price": "{{$random.integer}}"
}

### 주문 취소
@orderId = e4f052b8-62e5-4b22-98cb-943903ca0794
PUT http://localhost:9090/api/v1/orders/{{orderId}}/cancel


